<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList
{
    const TYPE = array(
        'NULL' => 0,
        'FRJQTZZSXFB' => 1,
        'ZRRSXFB' => 2,
        'BWMXWCFJLGAJ' => 3,
        'BWMXWCFJLZJWZ' => 4,
        'BWMXWCFJLGAJJT' => 5,
        'BWMXWCFJLMZJWMBZ' => 6,
        'BWMXWCFJLZJJWMJY' => 7,
        'BWMXWCFJLQWLJWMLY' => 8,
        'TJQYFRGGXYZHPJJG' => 9,
        'QYYCMLXX' => 10,
        'QIYEJBXX' => 11,
        'XBXZCF' => 12,
        'XBXZXK' => 13,
        'XZCF' => 48,
        'XZXK' => 49,
        'GWYXX' => 50,
        'GZYXX' => 51,
        'HSZYZGZXX' => 52,
        'JCFLYZRYXX' => 53,
        'JFDXJBXX' => 54,
        'JSGRRYXX' => 55,
        'JSZGXX' => 56,
        'JTYS' => 57,
        'JYJGFRXX' => 58,
        'KJCYZGXX' => 59,
        'LSZYZGZXX' => 60,
        'QJYXXSQJYXXSGBXX' => 61,
        'SFJDJGCYRYZGXX' => 62,
        'SHJZCYXX' => 63,
        'SHJZRYXX' => 64,
        'TDGJSXX' => 65,
        'WSZYJSZGKSWJXX' => 66,
        'XSZZGLXX' => 67,
        'ZCKJSXX' => 68,
        'ZFBZSQRXX' => 69,
        'QYHYSJ' => 70,
        'FRHEIMD'=>73,
        'FRHONGMD'=>74,
        'XZCJ'=>75,
        'XZJDJC'=>76,
        'XZJL'=>77,
        'XZQR'=>78,
        'XZQZ'=>79,
        //@position_type_80
        'TEST' => 500,
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
        ),
        IUserGroup::ID['QFZGGW'] => array(
            self::TYPE['TEST'],
            self::TYPE['TJQYFRGGXYZHPJJG'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRHONGMD'],
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['TJSXQQFSTDHYFWZX'] => array(),
        IUserGroup::ID['QSJJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QZFBGS'] => array(),
        IUserGroup::ID['QJYJ'] => array(
            self::TYPE['XSZZGLXX'],
            self::TYPE['QJYXXSQJYXXSGBXX'],
            self::TYPE['JYJGFRXX'],
            self::TYPE['JSZGXX'],
            self::TYPE['JSGRRYXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
        ),
        IUserGroup::ID['GAXQFJ'] => array(
            self::TYPE['BWMXWCFJLGAJ'],
            self::TYPE['BWMXWCFJLGAJJT'],
            self::TYPE['XZJL'],
        ),
        IUserGroup::ID['QWJW'] => array(
            self::TYPE['WSZYJSZGKSWJXX'],
            self::TYPE['JTYS'],
            self::TYPE['JFDXJBXX'],
            self::TYPE['HSZYZGZXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['XYMJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['JWZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QRSJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QTJJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QGXJ'] => array(),
        IUserGroup::ID['QGZW'] => array(),
        IUserGroup::ID['TJSXQQHTYSFWB'] => array(),
        IUserGroup::ID['TJSXQQWKHYZ'] => array(),
        IUserGroup::ID['LQZJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QYJJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['TJXQQCMXXJSYXGS'] => array(),
        IUserGroup::ID['QCZJ'] => array(
            self::TYPE['ZCKJSXX'],
            self::TYPE['KJCYZGXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['DSZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['TJSXQQSSSZWHYYCBS'] => array(),
        IUserGroup::ID['QRMTZX'] => array(),
        IUserGroup::ID['XKZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QSWUJ'] => array(),
        IUserGroup::ID['QFZB'] => array(),
        IUserGroup::ID['QWLJ'] => array(
            self::TYPE['BWMXWCFJLQWLJWMLY'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QRFB'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JCFLYZRYXX'],
            self::TYPE['GZYXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
        ),
        IUserGroup::ID['TJSXQQYFNYJSFWZX'] => array(),
        IUserGroup::ID['QXFB'] => array(
            self::TYPE['XZJDJC'],
        ),
        IUserGroup::ID['QNYNCW'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['ZBZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QGTZYFJ'] => array(),
        IUserGroup::ID['ZJWZ'] => array(
            self::TYPE['BWMXWCFJLZJWZ'],
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QZF'] => array(),
        IUserGroup::ID['YLQZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['WWZZ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['XQQXMSCZX'] => array(),
        IUserGroup::ID['XQQNZBGS'] => array(
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QSHWJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QSCJGJ'] => array(
            self::TYPE['BWMXWCFJLZJJWMJY'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QIYEJBXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['ZGNYYHGFYXGSTJYLQZH'] => array(),
        IUserGroup::ID['GJJXQFZX'] => array(),
        IUserGroup::ID['XQQKFQZGS'] => array(),
        IUserGroup::ID['QZSJ'] => array(),
        IUserGroup::ID['QCL'] => array(),
        IUserGroup::ID['QMZJ'] => array(
            self::TYPE['SHJZRYXX'],
            self::TYPE['SHJZCYXX'],
            self::TYPE['BWMXWCFJLMZJWMBZ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QQXJ'] => array(),
        IUserGroup::ID['QSWJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['CXDLGS'] => array(),
        IUserGroup::ID['XQQZHZFJ'] => array(),
        IUserGroup::ID['GHJ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['SXXQFZX'] => array(),
        IUserGroup::ID['QJRJ'] => array(),
        IUserGroup::ID['QZFJ'] => array(),
        IUserGroup::ID['TJSGAJTGLJXQZD'] => array(),
        IUserGroup::ID['QRMFY'] => array(
            self::TYPE['FRJQTZZSXFB'],
            self::TYPE['ZRRSXFB'],
        ),
        IUserGroup::ID['QWBGS'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QWZZB'] => array(
            self::TYPE['GWYXX']),
        IUserGroup::ID['QWXCB'] => array(),
        IUserGroup::ID['QWZFW'] => array(),
        IUserGroup::ID['QWZB'] => array(),
        IUserGroup::ID['QRMJCY'] => array(),
        IUserGroup::ID['QWWXB'] => array(),
        IUserGroup::ID['QWBB'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['TQW'] => array(),
        IUserGroup::ID['QGSL'] => array(),
        IUserGroup::ID['QKJJ'] => array(
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['QZJW'] => array(
            self::TYPE['ZFBZSQRXX'],
            self::TYPE['TDGJSXX'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QSTHJJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QCGW'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
        ),
        IUserGroup::ID['QYGJ'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['QZWFWB'] => array(
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['QTYJ'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['QYBJ'] => array(),
        IUserGroup::ID['QXTB'] => array(),
        IUserGroup::ID['XQQXZSPJ'] => array(),
        IUserGroup::ID['XQQWHHLYJ'] => array(),
        IUserGroup::ID['XQQXFJYZD'] => array(
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['TZB'] => array(
            self::TYPE['XZQR'],
        ),
        IUserGroup::ID['JMH'] => array(
            self::TYPE['XZCJ'],
            self::TYPE['XZJDJC'],
            self::TYPE['XZJL'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        IUserGroup::ID['CLN'] => array(
            self::TYPE['XZJDJC'],
            self::TYPE['XZQR'],
            self::TYPE['XZQZ'],
        ),
        //@position_usergroup
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
