<?php
namespace ResourceCatalog\Model;

interface IResourceCatalogTypeIdentify
{
    const TYPE_IDENTIFY = array(
        IResourceCatalog::TYPE['NULL'] => 0,
        IResourceCatalog::TYPE['FRJQTZZSXFB'] => 'FRJQTZZSXFB',
        IResourceCatalog::TYPE['ZRRSXFB'] => 'ZRRSXFB',
        IResourceCatalog::TYPE['BWMXWCFJLGAJ'] => 'BWMXWCFJLGAJ',
        IResourceCatalog::TYPE['BWMXWCFJLZJWZ'] => 'BWMXWCFJLZJWZ',
        IResourceCatalog::TYPE['BWMXWCFJLGAJJT'] => 'BWMXWCFJLGAJJT',
        IResourceCatalog::TYPE['BWMXWCFJLMZJWMBZ'] => 'BWMXWCFJLMZJWMBZ',
        IResourceCatalog::TYPE['BWMXWCFJLZJJWMJY'] => 'BWMXWCFJLZJJWMJY',
        IResourceCatalog::TYPE['BWMXWCFJLQWLJWMLY'] => 'BWMXWCFJLQWLJWMLY',
        IResourceCatalog::TYPE['TJQYFRGGXYZHPJJG'] => 'TJQYFRGGXYZHPJJG',
        IResourceCatalog::TYPE['QYYCMLXX'] => 'QYYCMLXX',
        IResourceCatalog::TYPE['QIYEJBXX'] => 'QIYEJBXX',
        IResourceCatalog::TYPE['XBXZCF'] => 'XBXZCF',
        IResourceCatalog::TYPE['XBXZXK'] => 'XBXZXK',
        IResourceCatalog::TYPE['XZCF'] => 'XZCF',
        IResourceCatalog::TYPE['XZXK'] => 'XZXK',
        IResourceCatalog::TYPE['TEST'] => 'TEST',
        IResourceCatalog::TYPE['GWYXX'] => 'GWYXX',
        IResourceCatalog::TYPE['GZYXX'] => 'GZYXX',
        IResourceCatalog::TYPE['HSZYZGZXX'] => 'HSZYZGZXX',
        IResourceCatalog::TYPE['JCFLYZRYXX'] => 'JCFLYZRYXX',
        IResourceCatalog::TYPE['JFDXJBXX'] => 'JFDXJBXX',
        IResourceCatalog::TYPE['JSGRRYXX'] => 'JSGRRYXX',
        IResourceCatalog::TYPE['JSZGXX'] => 'JSZGXX',
        IResourceCatalog::TYPE['JTYS'] => 'JTYS',
        IResourceCatalog::TYPE['JYJGFRXX'] => 'JYJGFRXX',
        IResourceCatalog::TYPE['KJCYZGXX'] => 'KJCYZGXX',
        IResourceCatalog::TYPE['LSZYZGZXX'] => 'LSZYZGZXX',
        IResourceCatalog::TYPE['QJYXXSQJYXXSGBXX'] => 'QJYXXSQJYXXSGBXX',
        IResourceCatalog::TYPE['SFJDJGCYRYZGXX'] => 'SFJDJGCYRYZGXX',
        IResourceCatalog::TYPE['SHJZCYXX'] => 'SHJZCYXX',
        IResourceCatalog::TYPE['SHJZRYXX'] => 'SHJZRYXX',
        IResourceCatalog::TYPE['TDGJSXX'] => 'TDGJSXX',
        IResourceCatalog::TYPE['WSZYJSZGKSWJXX'] => 'WSZYJSZGKSWJXX',
        IResourceCatalog::TYPE['XSZZGLXX'] => 'XSZZGLXX',
        IResourceCatalog::TYPE['ZCKJSXX'] => 'ZCKJSXX',
        IResourceCatalog::TYPE['ZFBZSQRXX'] => 'ZFBZSQRXX',
        IResourceCatalog::TYPE['QYHYSJ'] => 'QYHYSJ',
        IResourceCatalog::TYPE['FRHEIMD'] => 'FRHEIMD',
        IResourceCatalog::TYPE['FRHONGMD'] => 'FRHONGMD',
        IResourceCatalog::TYPE['XZCJ'] => 'xzcj',
        IResourceCatalog::TYPE['XZJDJC'] => 'xzjdjc',
        IResourceCatalog::TYPE['XZJL'] => 'xzjl',
        IResourceCatalog::TYPE['XZQR'] => 'xzqr',
        IResourceCatalog::TYPE['XZQZ'] => 'xzqz',
        //@position
    );
}
